spring:
  profiles: peer2
server:
  port: 8762

  eureka:
    instance:
      hostname: peer2
    client:
      ##registerWithEureka: false
      ##fetchRegistry: false
      serviceUrl :
        defaultZone:
        ##http://${eureka.instance.hostname}:${server.port}/eureka/
        http://peer1:8761/eureka/