spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testspringcloud?useUnicode=true&characterEncoding=utf8&characterSetResult=utf8
    username: root
    password: password

  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true