security:
  user: admin
  password: 123456
security.basic.enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      user.name: admin
      user.password: 123456
#management:
#  security:
#    enabled: false
server:
  port: 5000
logging:
  file: "logs/boot-admin-sample.log"
spring:
  application:
    name: server-admin
  boot:
      admin:
        routes:
          endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
        turbine:
          clusters: default
          location: turbine-service

