spring:
  application:
    name: eureka-client-two
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
server:
  port: 8763
logging:
  file: "logs/eureka-client-two.log"
management:
  security:
    enabled: false
