
spring:
   ##active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testspringcloud?useUnicode=true&characterEncoding=utf8&characterSetresult=utf8&serverTimezone=GMT%2B8
    username: root
    password: password
    jpa:
      hibernate:
        ddl-auto: update #第一次建表用create 后面用update
      show-sql: true
  redis:
    host: localhost
    port: 6379
    password:
      database: 1
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500

##management:
##  port: 9001
 ## security:
 ##   enabled: false


my:

  name: forezp
  age:  12
  number: ${random.int}

  uuid: ${random.uuid}

  max: ${random.int(10)}

  value: ${random.value}

  greeting: hi,i'm ${my.name}