eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 5000
spring:
  application:
    name: service-zuul

zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
      #serviceId: hiapi-v1
      ##如果不想用Ribbon做负载均衡,就制定URL,去掉SErviceId
      ##url: http://localhost:8762/eureka/

    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client

    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client

#所有API前面添加版本号
 # prefix: /v1

##如果想指定url又想做负载均衡，需自己维护服务注册列表，先关闭ribbon.eureka.enabled=false

## ribbon:
##  eureka:
##   enabled: false
##hiapi-v1:
##  ribbon:
##    listOfServers: http://localhost:8762 , http://localhost:8763
